### ISSUE TITLE
updateInterval not updating when passing different value when initializing

### ISSUE THREAD

**Issue by SebaBeltran** [seididieci/capacitor-backround-geolocation#12]
**Describe the bug**
When initializing with updateInterval: 30000 it doesn't update location every 30 seconds, instead get the location every 5 seconds or so. 

**To Reproduce**
Initialize the plugin with different value other than 10000 and check in the console every new location.  

**Expected behavior**
Time between location logs show match the updateInterval value. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android API 30
 - Browser Android Simulator

**Additional context**

**Comment by seididieci** [comment]
HI, I checked the code and noticed a typo in typescript definitions: updateInteval => updateInte**R**val...
I'm correcting it but i have to make a precisation on this value:

It sets the [updateInterval](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#public-locationrequest-setinterval-long-millis) Android location request option and, for convention, it sets the [fastestInterval](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#public-locationrequest-setfastestinterval-long-millis) at half of this value.

I could add another property to the configuration object but I wonder if it will make it too complicated, the two values are actually correlated.
