### ISSUE TITLE
iOS implementation

### ISSUE THREAD

**Issue by Callan003** [seididieci/capacitor-backround-geolocation#16]
Hello,

First of all I want to thank-you for this package! It works wonderful on Android!

Right now I am trying to implement it on iOS and I just saw that : 

> iOS
This plugin is not yet implemented iOS side, if someone wants to help I will appreciate it... <

Any news on this? Do you think it will be available on iOS soon? How can I help?

Thank-you!

**Comment by seididieci** [comment]
Hello,
Thank you for appreciating it.

I'm sorry but I have no concrete plans these days to bring in iOS support soon...
If you want and know how to help, the work needed is to replicate (if and where possible) the native part of the plugin, including:
- Checking whitch plugins options are compatible with iOS GPS settings (may need some mappping/translations)
- Creating the plugin class with matching functions and events.
- Creating iOS service to start GPS and send back position informations to capacitor APP side.

Tell me if you can, so we can start moving something...
Thanks!

**Comment by ramay2088** [comment]
It will be great if we can implement it in ios.
