### ISSUE TITLE
installation does not work with npm

### ISSUE THREAD

**Issue by DevCoderJR** [seididieci/capacitor-backround-geolocation#23]
Hello,

installation does not work with npm :

npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^2.4.7" from capacitor-background-geolocation@0.1.8
npm ERR! node_modules/capacitor-background-geolocation
npm ERR!   capacitor-background-geolocation@"*" from the root project

**Comment by seididieci** [comment]
Hi,
Sorry but seems this is an old project and is not updated with latest capacitor versions... It seems they removed the version used to make this plugin...
I suggest you to use an updated plugin that make the same thing and is updated to capacitor 5:

[https://github.com/capacitor-community/background-geolocation](https://github.com/capacitor-community/background-geolocation)
