### ISSUE TITLE
How to Stop Backgroundwatch ?

### ISSUE THREAD

**Issue by ReadyVRed** [seididieci/capacitor-backround-geolocation#5]
i can't find function to stop watching a location, instead i have to kill the app.. how to stop backgroundwatch listener onLocation ?

**Comment by seididieci** [comment]
Hi, there is currently no way to stop the service gettin location updates. 
I think this is a nice to have feature. I will take this into consideration and implement a Start/stop roundtrip when i get little time to do it.

**Comment by ReadyVRed** [comment]
Thanks!!
